// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "blocks/ring.mdx": () => import("../content/docs/blocks/ring.mdx?collection=docs"), "card component/cards-stack.mdx": () => import("../content/docs/card component/cards-stack.mdx?collection=docs"), "card component/image-inertia.mdx": () => import("../content/docs/card component/image-inertia.mdx?collection=docs"), "infinite scrollers/infinite-image-scroller-plane.mdx": () => import("../content/docs/infinite scrollers/infinite-image-scroller-plane.mdx?collection=docs"), "infinite scrollers/infinite-image-scroller.mdx": () => import("../content/docs/infinite scrollers/infinite-image-scroller.mdx?collection=docs"), "installation/add-utilities.mdx": () => import("../content/docs/installation/add-utilities.mdx?collection=docs"), "installation/getting-started.mdx": () => import("../content/docs/installation/getting-started.mdx?collection=docs"), "installation/install-nextjs.mdx": () => import("../content/docs/installation/install-nextjs.mdx?collection=docs"), "installation/install-tailwind-css.mdx": () => import("../content/docs/installation/install-tailwind-css.mdx?collection=docs"), "shader animation/glass-shader.mdx": () => import("../content/docs/shader animation/glass-shader.mdx?collection=docs"), "shader animation/sasta-lando.mdx": () => import("../content/docs/shader animation/sasta-lando.mdx?collection=docs"), "mouse follower/mouse-follower-2.mdx": () => import("../content/docs/mouse follower/mouse-follower-2.mdx?collection=docs"), "mouse follower/mouse-follower-3.mdx": () => import("../content/docs/mouse follower/mouse-follower-3.mdx?collection=docs"), "mouse follower/mouse-follower.mdx": () => import("../content/docs/mouse follower/mouse-follower.mdx?collection=docs"), "special ones/camera.mdx": () => import("../content/docs/special ones/camera.mdx?collection=docs"), "text animation/text-fade.mdx": () => import("../content/docs/text animation/text-fade.mdx?collection=docs"), "text animation/text-inertia.mdx": () => import("../content/docs/text animation/text-inertia.mdx?collection=docs"), }),
};
export default browserCollections;