import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// Original layouts developed after the reference study.
// Content is fictional; typography uses system fallbacks rather than licensed
// reference-site font files. No source-site assets or production JS are shipped.
const base = `*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font:16px/1.5 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;-webkit-font-smoothing:antialiased}h1,h2,p,ul{margin:0;padding:0}h1,h2{font-size:inherit;font-weight:400}a{color:inherit;text-underline-offset:4px;text-decoration-color:var(--border);transition:color 150ms,opacity 150ms}a:hover{text-decoration-color:currentColor}a:focus-visible,summary:focus-visible{outline:2px solid currentColor;outline-offset:4px}summary{list-style:none;cursor:pointer}summary::-webkit-details-marker{display:none}details>p{color:var(--muted);padding:12px 0 24px;font-size:14px;line-height:1.7}.skip{position:absolute;left:16px;top:-100px;background:var(--bg);padding:8px;z-index:10}.skip:focus{top:8px}footer{color:var(--muted);font-size:12px}section{scroll-margin-top:40px}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*{animation:none!important;transition:none!important}}`;
const document = (title, css, body) => `<!doctype html>
<!-- Pixel Perfect / editable portfolio template. Replace fictional names,
     biography, project descriptions, and example.com email addresses.
     This file runs without a framework or JavaScript. -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${title}. Selected work and contact details."><title>${title}</title><style>${base}${css}</style></head><body><a class="skip" href="#main">Skip to content</a>${body}</body></html>`;
const folioRow=(year,name,kind,mark,body)=>`<details><summary class="work-row"><span class="year">${year}</span><span class="project"><span class="icon" aria-hidden="true">${mark}</span>${name}</span><span class="kind">${kind}</span></summary><p>${body}</p></details>`;
const folio = document('Mira Sen — Product designer',`
:root{color-scheme:light dark;--bg:#fcfcfa;--fg:#292b26;--muted:#74776d;--border:#dcded6;--hover:#f0f1eb;--accent:#b34425}body{background:var(--bg);color:var(--fg)}main{max-width:900px;margin:auto;padding:64px 40px;display:grid;grid-template-columns:150px minmax(0,1fr);gap:48px 48px}header{grid-column:1;grid-row:1/5;align-self:start;position:sticky;top:48px;border-top:3px solid var(--accent);padding-top:16px}h1{font-size:18px;line-height:1.25;font-weight:500;letter-spacing:-.5px}.role{font-size:13px;margin-top:8px;color:var(--muted)}.intro{grid-column:2;max-width:490px;padding-top:16px;font-size:17px;line-height:1.7}.intro p+p{margin-top:20px;font-size:14px;color:var(--muted)}.intro a{font-weight:500}main>section{grid-column:2}h2{display:flex;align-items:center;gap:10px;font-size:12px;text-transform:uppercase;letter-spacing:.09em;color:var(--muted);margin-bottom:16px}h2:after{content:'';height:1px;flex:1;background:var(--border)}.work-row{display:grid;grid-template-columns:1fr auto;gap:3px 16px;align-items:center;padding:19px 0;border-bottom:1px solid var(--border)}.year{grid-column:2;grid-row:1;font-size:12px;color:var(--muted)}.project{grid-column:1;grid-row:1;font-size:18px;letter-spacing:-.4px;display:flex;gap:10px;align-items:center}.icon{font-size:17px;color:var(--accent);width:20px}.kind{grid-column:1;font-size:12px;color:var(--muted);padding-left:30px}.work-row:hover .project{color:var(--accent)}details[open] .work-row{border-color:var(--accent)}.work-row+p{padding:16px 0 20px 30px}.about{font-size:15px;line-height:1.8;color:var(--muted)}.text-entry{padding:12px 0}.text-entry summary{font-size:15px}.text-entry summary:hover{color:var(--accent)}.text-entry small{display:block;color:var(--muted);font-size:12px;margin-top:4px}.dock{display:flex;flex-direction:column;gap:10px;margin-top:32px}.dock a{font-size:13px;color:var(--muted);text-decoration:none}.dock a:hover{color:var(--accent)}.end{max-width:900px;margin:auto;padding:0 40px 32px;display:flex;justify-content:space-between;gap:16px;font-size:12px}@media(prefers-color-scheme:dark){:root{--bg:#191b18;--fg:#eeeeea;--muted:#a0a59a;--border:#373b32;--hover:#282b25;--accent:#ea8b64}}@media(max-width:620px){main{padding:32px 24px;grid-template-columns:1fr;gap:32px}header{position:static;grid-column:1;grid-row:auto;display:grid;grid-template-columns:1fr auto;align-items:baseline}.role{font-size:12px}.dock{grid-column:1/-1;flex-direction:row;gap:24px;margin-top:22px}.intro,main>section{grid-column:1}.intro{padding-top:0;font-size:16px}.end{padding:0 24px 24px}}
`, `
<main id="main"><header><h1>Mira Sen</h1><p class="role">Product designer</p><nav class="dock" aria-label="Page sections"><a href="#main">Hello</a><a href="#work">Projects</a><a href="#about">Off hours</a><a href="#writing">Fieldbook</a></nav></header>
<section class="intro"><p>I design software for people whose work happens away from a desk. Lately: helping a flower shop plan deliveries without covering the counter in sticky notes.</p><p>Here are a few <a href="#work">things I’ve shipped</a> and some <a href="#writing">notes from the process</a>. Have a wonderfully specific problem? <a href="mailto:mira@example.com">Tell me about it.</a></p></section>
<section class="section" id="work"><h2>From sketch to everyday use</h2>
${folioRow("2026","Stem Route","Delivery planning","✳","A morning dispatch board for a neighborhood florist. I mapped the packing routine, tested paper prototypes at the counter, and designed a route view that can be read with one hand on a crate.")}${folioRow("2026","Borrowed Hours","Equipment booking","◌","A booking system for a shared ceramics workshop. The schedule separates kiln time from bench time and makes cleanup part of the reservation, rather than an easily missed footnote.")}${folioRow("2025","Second Serving","Kitchen inventory","⊞","A stock check for a community kitchen. Large ingredient labels, quick quantity edits, and a printable shopping list replaced a spreadsheet that was hard to use during service.")}${folioRow("2025","Seat by the Window","Ticketing","⌁","A booking flow for a small cinema. I worked on the seat picker and confirmation messages, including a clear way to explain accessible seating before checkout.")}</section>
<section class="section" id="about"><h2>Off hours</h2><p class="about">Pune is home. I repair old desk lamps, help at a weekend pottery class, and keep a folder of unusually good instruction manuals. Most of my best questions start with watching someone do their job.</p></section>
<section id="writing"><h2>Fieldbook</h2><details class="text-entry"><summary>The counter is the real interface<small>August 2026</small></summary><p>At the flower shop, the screen sits behind wrapping paper and buckets. Testing from a clean desk hid the most obvious problem: nobody could reach the bottom row of controls.</p></details><details class="text-entry"><summary>A label beats a tooltip<small>May 2026</small></summary><p>We replaced a row of equipment icons with short names. The screen became less tidy, but new workshop members stopped asking which button booked the kiln.</p></details></section></main>
<footer class="end"><span>© 2026 Mira Sen</span><span>Pune, India</span></footer>`);
const indexRow=(name,year,body)=>`<li><details><summary><span>${name}</span><time>${year}</time></summary><p>${body}</p></details></li>`;
const index = document('Dev Mehta — Web engineer',`
:root{color-scheme:light dark;--bg:#fff;--fg:#263340;--muted:#79818a;--border:#d9dfe4;--blue:#2855a6}body{background:var(--bg);color:var(--fg);font-size:15px;line-height:1.6}main{max-width:780px;margin:auto;padding:48px 36px}header{display:grid;grid-template-columns:120px 1fr;gap:28px;border-top:1px solid var(--fg);padding:24px 0 34px;border-bottom:1px solid var(--border)}h1{font-size:22px;font-weight:500;line-height:1.2;letter-spacing:-.7px}.bio{font-size:14px}.bio p+p{margin-top:12px}.bio p:first-child{color:var(--blue)}.bio a{color:var(--blue)}section{display:grid;grid-template-columns:120px minmax(0,1fr);gap:28px;margin-top:32px}h2{font:12px/1.5 ui-monospace,SFMono-Regular,monospace;padding-top:12px;color:var(--muted)}ul{list-style:none}li{border-bottom:1px dashed var(--border)}summary{display:grid;grid-template-columns:1fr auto;align-items:center;gap:16px;padding:11px 0;line-height:24px}summary>span{display:flex;gap:12px;align-items:center}summary>span:before{content:'+';color:var(--blue);font:14px ui-monospace,monospace}details[open] summary>span:before{content:'−'}summary time{font:12px ui-monospace,monospace;color:var(--muted);font-variant-numeric:tabular-nums}summary:hover{color:var(--blue)}details>p{padding:0 24px 18px;font-size:14px}footer{margin-top:44px;padding-top:18px;border-top:1px solid var(--border);font-size:12px;color:var(--muted)}footer a{color:var(--blue)}@media(prefers-color-scheme:dark){:root{--bg:#141a21;--fg:#e2e8ef;--muted:#98a3af;--border:#36404c;--blue:#99b9fa}}@media(max-width:520px){main{padding:32px 24px}header{grid-template-columns:1fr;gap:20px}section{grid-template-columns:1fr;gap:6px;margin-top:26px}h2{font-size:12px}summary{padding:10px 0}}
`, `
<main id="main"><header><h1>Dev Mehta</h1><div class="bio"><p>Web engineer. Maps, archives, and public information.</p><p>I turn awkward datasets into pages people can actually use. Recent work includes bus stop timetables, a local history archive, and a repair directory.</p><p>The <a href="#projects">project log</a> covers what shipped. The <a href="#experiments">bench</a> is where I leave the unfinished bits.</p><p>For a technical hand or a second pair of eyes: <a href="mailto:dev@example.com">dev@example.com</a>.</p></div></header>
<section><h2>Practice</h2><ul>${indexRow("Civic web projects","2026","Independent work with libraries and community organizations. I handle the frontend, data imports, and the unglamorous work of keeping information current.")}${indexRow("Transit information","2025","Built timetable views from published service feeds. The main challenge was explaining exceptions clearly when the usual service changed.")}${indexRow("Archive systems","2024","Worked on search and catalog pages for a local collection, including support for uncertain dates and several names for the same place.")}</ul></section>
<section id="projects"><h2>Project log</h2><ul>${indexRow("Next Stop","2026","A bus stop page designed to load on a weak connection. Routes are grouped by direction, and service exceptions sit beside the relevant departure.")}${indexRow("Street Memory","2026","A searchable collection of neighborhood photographs. Visitors can browse by street even when the original catalog has incomplete dates.")}${indexRow("Fix Nearby","2025","A directory of repair shops organized by what they fix. Each record includes opening hours and the date the information was last checked.")}${indexRow("Rain Ledger","2025","A small viewer for daily rainfall records, with missing readings shown explicitly instead of quietly treated as zero.")}${indexRow("Noticeboard","2024","Printable event listings for a library foyer, generated from the same records used on its website.")}</ul></section><section id="experiments"><h2>On the bench</h2><ul>${indexRow("Search without spelling it right","2026","Testing forgiving place-name search against abbreviations, old street names, and the typos people actually make.")}${indexRow("The slow connection test","2025","Notes from loading public information pages on a throttled connection. The first useful sentence should arrive before the decorative parts.")}</ul></section><footer>Bengaluru · Usually working with a map open. <a href="mailto:dev@example.com">Write to me</a>.</footer></main>`);
const letterEntry=(name,description,body)=>`<details class="entry"><summary><span>${name}</span><small>${description}</small></summary><p>${body}</p></details>`;
const letter = document('Leela D’Souza — Reporter and editor',`
:root{color-scheme:light dark;--bg:#f9f7f2;--fg:#37302c;--muted:#80756e;--border:#d9d1c8;--red:#8c3d34}body{background:var(--bg);color:var(--fg)}main{max-width:820px;padding:42px 40px;margin:auto;display:grid;grid-template-columns:minmax(0,1.3fr) minmax(0,1fr);gap:42px 40px}header{grid-column:1/-1;border-top:2px solid var(--fg);padding-top:18px;columns:2;column-gap:40px}h1{column-span:all;font:400 38px/1.2 Georgia,serif;letter-spacing:-1px;padding-bottom:22px;margin-bottom:24px;border-bottom:1px solid var(--border)}header p{font:16px/1.8 Georgia,serif;break-inside:avoid;color:var(--fg)}header p+p{margin-top:16px}header a{color:var(--red)}.rule{display:none}section{margin:0}section+section{border-left:1px solid var(--border);padding-left:28px}h2{font:italic 22px/1.4 Georgia,serif;margin-bottom:10px;color:var(--red)}.entry{border-bottom:1px solid var(--border);padding:18px 0}.entry summary>span{display:block;font:18px/1.4 Georgia,serif}.entry summary small{display:block;font:13px/1.65 system-ui,sans-serif;color:var(--muted);margin-top:8px}.entry summary:hover>span{color:var(--red)}.entry>p{font:15px/1.8 Georgia,serif;padding:12px 0 4px}.contact{grid-column:1/-1;font:18px/1.7 Georgia,serif;padding-top:22px;border-top:2px solid var(--fg)}.contact a{color:var(--red)}footer{grid-column:1/-1;margin-top:-16px;font-size:12px}@media(prefers-color-scheme:dark){:root{--bg:#211e1b;--fg:#ece5da;--muted:#b5a89b;--border:#4e453c;--red:#d7a18b}}@media(max-width:580px){main{display:block;padding:32px 24px}header{columns:1}h1{font-size:34px}section{margin-top:34px}section+section{border-left:0;padding-left:0}.contact{margin-top:36px}footer{margin-top:24px}}
`, `
<main id="main"><header><h1>Leela D’Souza</h1><p>I write about food through the people who grow it, sell it, and cook it for everyone else. My reporting starts in markets and kitchens, usually before breakfast.</p><p>My latest project, <a href="#tiffin">The Tiffin Ledger</a>, follows the handwritten notebooks behind family lunch businesses in Mumbai.</p><p>I take on reported features, oral histories, and editing projects. I like a patient interview and a detail that refuses to fit the first draft.</p></header>
<section><h2>Reported work</h2>${letterEntry("Before the Shutters Rise","A morning at the wholesale vegetable market.","A reported feature following three vendors through unloading, pricing, and the first customers of the day. The story grew out of repeated visits rather than a single interview.")}<div id="tiffin">${letterEntry("The Tiffin Ledger","Lunch businesses, told through their notebooks.","An oral history project about household recipes becoming daily work. The interviews track portions, prices, substitutions, and the knowledge that never makes it onto the page.")}</div>${letterEntry("Salt Season","Along the coast with small-scale salt makers.","A photo essay and accompanying text about weather, labor, and the short window for harvesting. The editing preserves the sequence of a working day.")}${letterEntry("A Table for Twelve","How a neighborhood dining room stays open.","Conversations with the cooks, regulars, and volunteers who keep an inexpensive lunch service running. A story about maintenance as much as food.")}</section><section><h2>Desk notes</h2>${letterEntry("Ask about the second batch","A better question for a kitchen interview.","The first batch often follows the recipe. The second reveals what changed: the heat, the crowd, a missing ingredient. That is where the useful questions begin.")}${letterEntry("Keep the shopping list","What survives after an interview.","Receipts and shopping lists can place a story in a particular week more precisely than a polished recollection. I ask before keeping or photographing them.")}</section><p class="contact">Have a story worth spending time with?<br><a href="mailto:leela@example.com">leela@example.com</a></p><footer>© 2026 Leela D’Souza · Mumbai</footer></main>`);
const output=fileURLToPath(new URL('../../public/portfolios/',import.meta.url));
mkdirSync(output,{recursive:true});
for(const [name,html] of Object.entries({folio,index,letter}))writeFileSync(`${output}${name}.html`,html);
console.log('Generated three distinct portfolio previews.');
