import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// Original layouts developed after the reference study.
// Content is fictional; typography uses system fallbacks rather than licensed
// reference-site font files. No source-site assets or production JS are shipped.
const base = `*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font:16px/1.5 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;-webkit-font-smoothing:antialiased}h1,h2,p,ul{margin:0;padding:0}h1,h2{font-size:inherit;font-weight:400}a{color:inherit;text-underline-offset:4px;text-decoration-color:var(--border);transition:color 150ms,opacity 150ms}a:hover{text-decoration-color:currentColor}a:focus-visible,summary:focus-visible{outline:2px solid currentColor;outline-offset:4px}summary{list-style:none;cursor:pointer}summary::-webkit-details-marker{display:none}details>p{color:var(--muted);padding:12px 0 24px;font-size:14px;line-height:1.7}.skip{position:absolute;left:16px;top:-100px;background:var(--bg);padding:8px;z-index:10}.skip:focus{top:8px}footer{color:var(--muted);font-size:12px}section{scroll-margin-top:40px}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*{animation:none!important;transition:none!important}}`;
const document = (title, css, body) => `<!doctype html>
<!-- Pixel Perfect / editable portfolio template. Replace fictional names,
     biography, project descriptions, and example.com email addresses.
     This file runs without a framework or JavaScript. -->
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${title}. Selected work and contact details."><title>${title}</title><style>${base}${css}</style></head><body><a class="skip" href="#main">Skip to content</a>${body}</body></html>`;
const folioRow=(year,name,kind,mark,body)=>`<details><summary class="work-row"><span class="year">${year}</span><span class="project"><span class="icon" aria-hidden="true">${mark}</span>${name}</span><span class="kind">${kind}</span></summary><p>${body}</p></details>`;
const folio = document('Tara Rao — Visual designer',`
:root{color-scheme:light dark;--bg:#fcfcfa;--fg:#292b26;--muted:#74776d;--border:#dcded6;--hover:#f0f1eb;--accent:#b34425}body{background:var(--bg);color:var(--fg)}main{max-width:900px;margin:auto;padding:64px 40px;display:grid;grid-template-columns:150px minmax(0,1fr);gap:48px 48px}header{grid-column:1;grid-row:1/5;align-self:start;position:sticky;top:48px;border-top:3px solid var(--accent);padding-top:16px}h1{font-size:18px;line-height:1.25;font-weight:500;letter-spacing:-.5px}.role{font-size:13px;margin-top:8px;color:var(--muted)}.intro{grid-column:2;max-width:490px;padding-top:16px;font-size:17px;line-height:1.7}.intro p+p{margin-top:20px;font-size:14px;color:var(--muted)}.intro a{font-weight:500}main>section{grid-column:2}h2{display:flex;align-items:center;gap:10px;font-size:12px;text-transform:uppercase;letter-spacing:.09em;color:var(--muted);margin-bottom:16px}h2:after{content:'';height:1px;flex:1;background:var(--border)}.work-row{display:grid;grid-template-columns:1fr auto;gap:3px 16px;align-items:center;padding:19px 0;border-bottom:1px solid var(--border)}.year{grid-column:2;grid-row:1;font-size:12px;color:var(--muted)}.project{grid-column:1;grid-row:1;font-size:18px;letter-spacing:-.4px;display:flex;gap:10px;align-items:center}.icon{font-size:17px;color:var(--accent);width:20px}.kind{grid-column:1;font-size:12px;color:var(--muted);padding-left:30px}.work-row:hover .project{color:var(--accent)}details[open] .work-row{border-color:var(--accent)}.work-row+p{padding:16px 0 20px 30px}.about{font-size:15px;line-height:1.8;color:var(--muted)}.text-entry{padding:12px 0}.text-entry summary{font-size:15px}.text-entry summary:hover{color:var(--accent)}.text-entry small{display:block;color:var(--muted);font-size:12px;margin-top:4px}.dock{display:flex;flex-direction:column;gap:10px;margin-top:32px}.dock a{font-size:13px;color:var(--muted);text-decoration:none}.dock a:hover{color:var(--accent)}.end{max-width:900px;margin:auto;padding:0 40px 32px;display:flex;justify-content:space-between;gap:16px;font-size:12px}@media(prefers-color-scheme:dark){:root{--bg:#191b18;--fg:#eeeeea;--muted:#a0a59a;--border:#373b32;--hover:#282b25;--accent:#ea8b64}}@media(max-width:620px){main{padding:32px 24px;grid-template-columns:1fr;gap:32px}header{position:static;grid-column:1;grid-row:auto;display:grid;grid-template-columns:1fr auto;align-items:baseline}.role{font-size:12px}.dock{grid-column:1/-1;flex-direction:row;gap:24px;margin-top:22px}.intro,main>section{grid-column:1}.intro{padding-top:0;font-size:16px}.end{padding:0 24px 24px}}
`, `
<main id="main"><header><h1>Tara Rao</h1><p class="role">Visual designer</p><nav class="dock" aria-label="Page sections"><a href="#main">Intro</a><a href="#work">Selected work</a><a href="#about">In the studio</a><a href="#writing">Process notes</a></nav></header>
<section class="intro"><p>My projects tend to end up in someone’s hands: a concert programme, a folded map, a book with a well-used spine. I design identities and publications, then help them find their way onto the web.</p><p>Below is a selection of <a href="#work">recent commissions</a>. I also keep <a href="#writing">process notes</a> on the decisions that rarely make it into the final presentation. For new work, <a href="mailto:tara@example.com">send a brief</a>.</p></section>
<section class="section" id="work"><h2>Recent commissions</h2>${folioRow("2026","After the Encore","Festival identity","✳","An identity for a three-night chamber music festival. The same modular lettering runs across street posters, stage schedules, and a website visitors can check while waiting in line.")}${folioRow("2026","A Fold in the River","Walking map","◌","A pocket guide commissioned by a riverside arts group. I walked the route with the organizers before designing a map that folds to show one stretch at a time.")}${folioRow("2025","Small Editions","Publisher website","⊞","A catalogue for an independent poetry press. Each book gets space for a sample spread, a short extract, and the details a reader would check in a bookshop.")}${folioRow("2025","Room for a Second Chair","Exhibition graphics","⌁","Labels and a printed guide for an exhibition of repaired furniture. The captions separate the original maker from the person who restored each piece.")}</section>
<section class="section" id="about"><h2>In the studio</h2><p class="about">I share a studio in Ahmedabad with a bookbinder. There is usually a paper sample on the windowsill and a print drying on the only spare chair. I work directly with editors, organizers, and small cultural teams.</p></section>
<section id="writing"><h2>Process notes</h2><details class="text-entry"><summary>Print it at the size people will hold<small>July 2026</small></summary><p>A map that felt generous on screen became crowded when folded. Printing the first draft early changed the route labels, the key, and where we put the emergency contact.</p></details><details class="text-entry"><summary>The back cover has a job too<small>March 2026</small></summary><p>For a programme people carry between venues, the back cover is the quickest place to find the next address. We moved the sponsor credits inside and gave that surface to the schedule.</p></details></section></main>
<footer class="end"><span>© 2026 Tara Rao</span><span>Ahmedabad · Identity &amp; print</span></footer>`);
const indexRow=(name,year,body)=>`<li><details><summary><span>${name}</span><time>${year}</time></summary><p>${body}</p></details></li>`;
const index = document('Ishan Bose — Audio software engineer',`
:root{color-scheme:light dark;--bg:#fff;--fg:#263340;--muted:#79818a;--border:#d9dfe4;--blue:#2855a6}body{background:var(--bg);color:var(--fg);font-size:15px;line-height:1.6}main{max-width:780px;margin:auto;padding:48px 36px}header{display:grid;grid-template-columns:120px 1fr;gap:28px;border-top:1px solid var(--fg);padding:24px 0 34px;border-bottom:1px solid var(--border)}h1{font-size:22px;font-weight:500;line-height:1.2;letter-spacing:-.7px}.bio{font-size:14px}.bio p+p{margin-top:12px}.bio p:first-child{color:var(--blue)}.bio a{color:var(--blue)}section{display:grid;grid-template-columns:120px minmax(0,1fr);gap:28px;margin-top:32px}h2{font:12px/1.5 ui-monospace,SFMono-Regular,monospace;padding-top:12px;color:var(--muted)}ul{list-style:none}li{border-bottom:1px dashed var(--border)}summary{display:grid;grid-template-columns:1fr auto;align-items:center;gap:16px;padding:11px 0;line-height:24px}summary>span{display:flex;gap:12px;align-items:center}summary>span:before{content:'+';color:var(--blue);font:14px ui-monospace,monospace}details[open] summary>span:before{content:'−'}summary time{font:12px ui-monospace,monospace;color:var(--muted);font-variant-numeric:tabular-nums}summary:hover{color:var(--blue)}details>p{padding:0 24px 18px;font-size:14px}footer{margin-top:44px;padding-top:18px;border-top:1px solid var(--border);font-size:12px;color:var(--muted)}footer a{color:var(--blue)}@media(prefers-color-scheme:dark){:root{--bg:#141a21;--fg:#e2e8ef;--muted:#98a3af;--border:#36404c;--blue:#99b9fa}}@media(max-width:520px){main{padding:32px 24px}header{grid-template-columns:1fr;gap:20px}section{grid-template-columns:1fr;gap:6px;margin-top:26px}h2{font-size:12px}summary{padding:10px 0}}
`, `
<main id="main"><header><h1>Ishan Bose</h1><div class="bio"><p>Software for recording rooms and rehearsal spaces.</p><p>I build the tools around a session: finding a take, tracking a borrowed microphone, or getting everyone the right version of a mix. I started by fixing the spreadsheets in a rehearsal studio.</p><p>The <a href="#projects">release shelf</a> holds the finished tools. <a href="#experiments">Soundchecks</a> collects the smaller tests that might become something.</p><p>Something in your workflow keeps getting in the way? <a href="mailto:ishan@example.com">ishan@example.com</a>.</p></div></header>
<section><h2>Background</h2><ul>${indexRow("Independent audio tools","2026","Working with musicians and studio managers to build small browser tools. My part covers interface design, file handling, and making recovery from mistakes straightforward.")}${indexRow("Session operations","2025","Maintained booking and equipment systems for a rehearsal space. Most improvements came from watching what the evening shift had to write down twice.")}${indexRow("Live recording","2024","Supported small ensemble recordings, organized session files, and learned why a clear filename can matter as much as another feature.")}</ul></section>
<section id="projects"><h2>Release shelf</h2><ul>${indexRow("Take Twelve","2026","A browser-based take log. Notes stay attached to the recording time so an editor can find the good ending without listening through the whole session again.")}${indexRow("Patch Receipt","2026","An equipment checkout log for shared studios. It records the cable, adapter, or microphone actually borrowed, along with who is bringing it back.")}${indexRow("Mix Envelope","2025","A review page for successive mixes. Listeners can leave comments at a time position and see which version they are hearing before pressing play.")}${indexRow("Set Interval","2025","A running-order planner that includes changeovers. Moving one performance updates the remaining times without overwriting the breaks the crew needs.")}${indexRow("Quiet Hours","2024","A booking calendar for rooms with different noise limits. It shows which sessions can run next door to each other and where a buffer is needed.")}</ul></section><section id="experiments"><h2>Soundchecks</h2><ul>${indexRow("Finding the clipped peak","2026","A waveform experiment that marks likely clipping for a closer listen. It flags a place to inspect, rather than pretending a picture can judge the recording.")}${indexRow("One folder, two spellings","2025","A file naming study built from messy session folders. The goal is to find duplicates without renaming or deleting the originals.")}</ul></section><footer>Kolkata · Tools made between sessions. <a href="mailto:ishan@example.com">Start a conversation</a>.</footer></main>`);
const output=fileURLToPath(new URL('../../public/portfolios/',import.meta.url));
mkdirSync(output,{recursive:true});
for(const [name,html] of Object.entries({folio,index}))writeFileSync(`${output}${name}.html`,html);
console.log('Generated Folio and Index portfolio previews.');
